#!/bin/bash
# Bot Management - wszystkie narzędzia monitoringu

echo "=================================================="
echo "🤖 BOT MONITORING TOOLS"
echo "=================================================="
echo ""
echo "Dostępne komendy:"
echo ""
echo "1. Podgląd dashboard (terminal):"
echo "   python3 ~/.openclaw/workspace/bot_monitor.py"
echo ""
echo "2. Live monitoring (odświeżanie co 30s):"
echo "   ~/.openclaw/workspace/monitor_live.sh"
echo ""
echo "3. Generuj raport HTML:"
echo "   python3 ~/.openclaw/workspace/generate_dashboard.py"
echo "   → Otwórz: ~/.openclaw/workspace/memory/bot_dashboard.html"
echo ""
echo "4. Eksportuj raport JSON:"
echo "   python3 ~/.openclaw/workspace/bot_monitor.py export"
echo ""
echo "5. Statystyki (JSON):"
echo "   python3 ~/.openclaw/workspace/bot_monitor.py stats"
echo ""
echo "6. Przeglądaj wyniki backtestów:"
echo "   python3 ~/.openclaw/workspace/view_backtest_results.py"
echo ""
echo "=================================================="
echo "Pliki i lokalizacje:"
echo "=================================================="
echo ""
echo "📊 Monitoring bazy danych:"
echo "   ~/.openclaw/workspace/memory/bot_monitor.db"
echo ""
echo "📈 Dashboard HTML:"
echo "   ~/.openclaw/workspace/memory/bot_dashboard.html"
echo ""
echo "📝 Logi bota:"
echo "   ~/.openclaw/workspace/memory/passivbot_logs/unified_bot.log"
echo ""
echo "📁 Wyniki backtestów:"
echo "   ~/.openclaw/workspace/memory/backtest_results/"
echo ""
echo "=================================================="
